from os.path import dirname, abspath
from os import environ as env

CORE_ROOT = dirname(dirname(abspath(__file__)))
PROJECT_ROOT = dirname(CORE_ROOT)

STATIC_URL = env['STATIC_URL']
CDN_URL = env['CDN_URL']
AWS_STORAGE_BUCKET_NAME = env['AWS_STORAGE_BUCKET_NAME']
AWS_STORAGE_BUCKET_URL = env['AWS_STORAGE_BUCKET_URL']
AWS_STORAGE_BUCKET_KEY = env['AWS_STORAGE_BUCKET_KEY']

AWS_ACCESS_KEY_ID = env['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = env['AWS_SECRET_ACCESS_KEY']
DROPBOX_APP_KEY = env['DROPBOX_APP_KEY']
DROPBOX_APP_SECRET = env['DROPBOX_APP_SECRET']
