project_name: juxtapose
service_name: "{{ project_name|lower }}"
gitdeploy_version: "1.0.6"
service_port: "{{ juxtapose_port }}"
python_version: "3.7.7"
python: /home/apps/sites/juxtapose/.venv/bin/python
# type: flask
nginx_template: juxtapose.conf

playbooks:
  - playbook.deploy-repo.yml
  - playbook.deploy-web.yml
  - playbook.restart.yml

# these will be merged with deployment-specific env into init_env
init_env_common:
  PROJECT_NAME: "{{ project_name }}"
  APPLICATION_DOMAINS: "{{ domains }}" # space-delimited
  FLASK_SECRET_KEY: "{{ vault_flask_secret_key }}"
  AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key_id }}"
  AWS_SECRET_ACCESS_KEY: "{{ vault_aws_secret_access_key }}"
  DROPBOX_APP_KEY: "{{ vault_dropbox_app_key }}"
  DROPBOX_APP_SECRET: "{{ vault_dropbox_app_secret }}"
  FLASK_SETTINGS_MODULE: "core.settings"
  FLASK_SETTINGS_FILE: "core/settings.py"


# Flask specific configs
static_dir: "{{ application_dir }}/static"

application_dir: "{{ deploy_dir }}/website"

# nginx_conf: "{{ deploy_dir }}/nginx/conf.d/{{ project_name }}.conf"

# Configs below will not usually change
deploy_dir: "{{ install_root }}/{{ project_name }}"
env_file: "{{ deploy_dir }}/.env"
envrc_file: "{{ deploy_dir }}/.envrc"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
requirements_file: "{{ deploy_dir }}/requirements.txt"
virtualenv: "{{ virtualenv_root }}/venv"
wsgi_application: "core.wsgi:application"
static_service: "s3"
static_dest: "s3://{{ static_bucket }}/{{ project_name }}"

# Configs common to all projects
application_user: apps
install_root: /home/{{ application_user }}/sites
virtualenv_root: "{{ deploy_dir }}"
