domains: "{{ project_name }}.knilab.com"
static_bucket: "media.knilab.com"
gunicorn_reload: True # generally True on staging only
ssl:
  ssl_certificate: "/etc/nginx/ssl/knilab/knilab-bundle.crt"
  ssl_certificate_key: "/etc/nginx/ssl/knilab/knilab-com.key"

init_env_stg:
  STATIC_URL: "//media.knilab.com/{{ project_name }}/"
  AWS_STORAGE_BUCKET_NAME: "uploads.knilab.com"
  AWS_STORAGE_BUCKET_URL: "//s3.amazonaws.com/uploads.knilab.com/"
  AWS_STORAGE_BUCKET_KEY: "{{ project_name }}"
  CDN_URL: "https://s3.amazonaws.com/cdn.knightlab.com/libs/juxtapose/dev/"

# Note that env vars set in the upstart config will also be set when using the
# modified manage.py file for db migration and custom management commands
init_env: "{{ init_env_common|combine(init_env_stg) }}"
