- hosts: "{{ env }}"
  vars_files:
    - "{{ config_dir }}/config.common.yml"
    - "{{ config_dir }}/config.{{ env }}.yml"
  gather_facts: false

  roles:
    - role: knightlab
    - role: deploy
    - role: nginx
